google_analytics: G-MSP510LCQB
theme: jekyll-theme-cayman
repository_url: https://github.com/microsoft/Table-Pretraining
paper_url: https://arxiv.org/pdf/2107.07653.pdf
contact_mail: qian.liu@buaa.edu.cn